version: '3.8'
services:
  supabase:
    image: supabase/postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - supabase-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - supabase
  frontend:
    build: .
    ports:
      - '5173:5173'
    env_file:
      - ./.env
    depends_on:
      - backend
volumes:
  supabase-data: