name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ '.', 'backend' ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.dir }}
      - name: Build
        run: npm run build || true
        working-directory: ${{ matrix.dir }}
      - name: TypeScript type-check
        run: npm run type-check

      - name: Ensure no JS drift
        run: |
          ! find . -type f \( -name "*.js" -o -name "*.jsx" \) \
            ! -path "*/node_modules/*" \
            ! -path "*/dist/*" \
            | grep .